name: IAM Bootstrap for EKS

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS Region to deploy the IAM stack"
        required: true
        default: "us-east-1"
        type: string
      terraform_user_name:
        description: "IAM user name for Terraform"
        required: true
        default: "terraform-user"
        type: string



jobs:
  iam:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-terraform-role
          aws-region: ${{ inputs.aws_region }}

      - name: Deploy IAM CloudFormation stack
        run: |
          aws cloudformation deploy \
            --region ${{ inputs.aws_region }} \
            --stack-name eks-iam-stack \
            --template-file iam-eks.yaml \
            --parameter-overrides TerraformUserName=${{ inputs.terraform_user_name }} \
            --capabilities CAPABILITY_NAMED_IAM
